### ISSUE TITLE
RealmManager class creates Realm instances that are never closed, thus creating native leaks

### ISSUE THREAD

**Issue by Zhuinden** [Zeyad-37/UseCases#1]
https://github.com/Zeyad-37/GenericUseCase/blob/master/DataAccessLayer/src/main/java/com/zeyad/genericusecase/data/db/RealmManager.java

**Comment by Zeyad-37** [comment]
Hey thanks for the report. I have figured out this problem a while ago and already working on fixing it. Also if you want to contribute to fix it that would be great thanks again.

**Comment by Zeyad-37** [comment]
Hey i have just fixed the bug. Please check out the latest version.
